version: '3'
services:
  mosquitto:
    container_name: mosquitto
    restart: always
    build: .
    volumes:
      - ${PWD}/auth-plugin.conf:/etc/mosquitto.d/auth-plugin.conf
      - ./mosquitto.conf:/etc/mosquitto/mosquitto.conf
      - ./certs:/var/lib/mosquitto
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8883:8883"
    depends_on:
      - redis
    labels:
      - "local.example.description=Mosquitto MQTT server"

  redis:
    container_name: redis-mqtt
    restart: always
    image: redis:6.0.6-alpine
    volumes:
      - ${PWD}/tmp/data:/data
    ports:
      - "6378:6379"
