version: '3'
services:
  mosquitto:
    container_name: mosquitto
    restart: always
    build: .
    networks:
      - mosquitto-net
    ports:
      - 1883:1883
      - 8083:8083
      - 8883:8883
      - 80:80
      - 443:443
    depends_on:
      - redis
    environment:
      - DOMAIN=mqtt.almondhydroponics.com
      - EMAIL=almond.froyo@gmail.com
    volumes:
      - ./auth-plugin.conf:/etc/mosquitto.d/auth-plugin.conf
      - ./letsencrypt:/etc/letsencrypt
      - ./scripts:/scripts
  redis:
    container_name: redis-mqtt
    build:
      context: ./redis
    restart: always
    privileged: true
    command: sh -c "/redis/init.sh"
    volumes:
      - ./tmp/data:/data
#    ports:
#      - "6379:6379"
    networks:
      - mosquitto-net
networks:
  mosquitto-net:
