version: '3'
services:
  mosquitto:
    container_name: mosquitto
    restart: always
    build: .
    networks:
      - almond-net
    ports:
      - 1883:1883
      - 8083:8083
      - 8883:8883
      - 80:80
    environment:
      - DOMAIN=almondhydroponics.com
      - EMAIL=francismasha96@gmail.com
    volumes:
      - ./mosquitto.conf:/mosquitto/conf/mosquitto.conf
      - ./mosquitto.log:/mosquitto/log/mosquitto.log
      - ./mosquitto/conf/:/mosquitto/conf
      - ./mosquitto/log/:/mosquitto/log
      - ./letsencrypt:/etc/letsencrypt
      - ./scripts:/scripts
networks:
  almond-net:
    external:
      name: almond-net
